'use client';
import Image from 'next/image';
import { imageByKey } from '@/lib/site';
import { useState } from 'react';
import { Breadcrumbs } from '@/components/Breadcrumbs';
const sections = [
  { title:'Terracotta care basics', body:'Terracotta is porous, breathable, and loved by plants because it helps roots stay aerated. Clean gently, avoid harsh soaps, and let the piece dry naturally after rinsing.' },
  { title:'Watering and drainage', body:'Always make sure plant-ready pots have clear drainage. Terracotta will dry faster than glazed ceramics, so check moisture levels more frequently in hot weather.' },
  { title:'Indoor placement', body:'For indoor styling, place pots where they receive the light your chosen plant prefers. Use saucers or trays under drainage holes to protect wood and stone surfaces.' },
  { title:'Outdoor durability', body:'Our outdoor-ready pieces are made for Kenyan sun, rain, and dust. Raise very large pots slightly off the ground for airflow and long-term surface protection.' }
];
export default function Page(){ const [active, setActive] = useState(0); return <main className="container-shell py-12 md:py-16"><Breadcrumbs items={[['Home','/'],['Care Guide','/care-guide']]} /><div className="mt-8 text-center"><div className="text-xs font-semibold uppercase tracking-[0.22em] text-[#B66A3C]">Help</div><h1 className="mt-4 serif-display text-6xl text-[#3d2a20]">Care Guide</h1><p className="mx-auto mt-4 max-w-3xl text-lg leading-8 text-[#76675c]">Simple practical guidance for getting the best from your terracotta pots and their plant pairings.</p></div><div className="mt-10 flex flex-wrap justify-center gap-3">{sections.map((section,idx)=><button key={section.title} onClick={()=>setActive(idx)} className={`rounded-full px-5 py-3 text-xs font-semibold uppercase tracking-[0.18em] ${active===idx?'bg-[#5A3422] text-white':'border border-[#e6d9cd] bg-white text-[#7d6d60]'}`}>{section.title}</button>)}</div><div className="mt-10 grid gap-8 lg:grid-cols-[0.95fr_1.05fr]"><div className="overflow-hidden rounded-[2rem]"><Image src={imageByKey.clay} alt="Care guide" width={1200} height={900} className="h-full w-full object-cover" /></div><div className="rounded-[2rem] border border-[#e6d9cd] bg-white p-8"><h2 className="serif-display text-5xl text-[#4b3428]">{sections[active].title}</h2><p className="mt-5 text-base leading-9 text-[#726357]">{sections[active].body}</p><div className="mt-8 grid gap-4 md:grid-cols-2">{['Use a saucer indoors to protect surfaces.','Let clay dry fully between deep cleans.','Avoid harsh chemical cleaners.','Check soil faster in hot weather.'].map((tip)=><div key={tip} className="rounded-2xl bg-[#F7F2EA] p-4 text-sm leading-7 text-[#6b5d53]">{tip}</div>)}</div></div></div></main>}
