import type { ManagedPageRecord } from '@/lib/cms';
import type { SearchableEntry } from '@/lib/search-utils';

export type AdminHelpEntry = SearchableEntry & {
  href: string;
  destination: string;
  actionLabel: string;
  steps: string[];
};

function pageNames(managedPages: ManagedPageRecord[]) {
  return managedPages.map((page) => page.label).join(', ');
}

export function getAdminHelpEntries(managedPages: ManagedPageRecord[] = []): AdminHelpEntry[] {
  const managedPageList = pageNames(managedPages);

  return [
    {
      id: 'admin-help:add-product',
      category: 'admin',
      kind: 'answer',
      title: 'Add a new product',
      summary:
        'Use the Products area to create a new clay form, upload images, confirm prices, and save it to the live catalog.',
      label: 'Products',
      href: '/admin?tab=products',
      destination: 'Products tab',
      actionLabel: 'Open Products',
      keywords: [
        'add product',
        'new product',
        'create product',
        'catalog',
        'data entry',
        'price',
        'pot only',
        'pot and plant',
        'gallery',
      ],
      steps: [
        'Open Products.',
        'Choose New Product.',
        'Type the product name. The slug and SKU will fill automatically, but you can still edit them.',
        'Choose the category, available sizes, and prices.',
        'Upload the clay-only and plant version images, then save the product.',
      ],
    },
    {
      id: 'admin-help:product-images',
      category: 'admin',
      kind: 'answer',
      title: 'Change product images or gallery',
      summary:
        'Product image editing lives in the Products area, where you can replace the main image, add gallery images, and keep clay-only and plant versions separate.',
      label: 'Products',
      href: '/admin?tab=products',
      destination: 'Products tab',
      actionLabel: 'Open Products',
      keywords: [
        'change image',
        'product image',
        'gallery',
        'upload photo',
        'replace picture',
        'main image',
        'small gallery',
        'pot image',
        'plant image',
      ],
      steps: [
        'Open Products and choose the product you want to update.',
        'Go to the image and gallery area in the product editor.',
        'Upload a new main image or add more gallery images.',
        'Remove any image that should no longer appear.',
        'Save the product so the live page updates.',
      ],
    },
    {
      id: 'admin-help:slug-sku',
      category: 'admin',
      kind: 'answer',
      title: 'Update the slug or SKU',
      summary:
        'The system fills slug and SKU automatically from the product details, but you can switch them to custom values when needed.',
      label: 'Products',
      href: '/admin?tab=products',
      destination: 'Products tab',
      actionLabel: 'Open Products',
      keywords: [
        'slug',
        'sku',
        'change slug',
        'change sku',
        'custom slug',
        'custom sku',
        'auto slug',
        'auto sku',
      ],
      steps: [
        'Open Products and select the product.',
        'Find the slug and SKU fields in the editor.',
        'Leave them in Auto if the generated version is right.',
        'If you need a custom version, type over the value.',
        'Save the product when you are done.',
      ],
    },
    {
      id: 'admin-help:orders',
      category: 'admin',
      kind: 'answer',
      title: 'Process or update an order',
      summary:
        'Orders are handled in the Orders area, where you can review customer details, update status, and keep delivery notes clear.',
      label: 'Orders',
      href: '/admin?tab=orders',
      destination: 'Orders tab',
      actionLabel: 'Open Orders',
      keywords: [
        'order',
        'update order',
        'order status',
        'shipping',
        'tracking',
        'delivery',
        'customer order',
        'checkout',
      ],
      steps: [
        'Open Orders.',
        'Search for the order number or customer name.',
        'Open the order and review the items and payment details.',
        'Choose the new status, add notes if needed, and save.',
        'Use the tracking and delivery details to keep the customer updates correct.',
      ],
    },
    {
      id: 'admin-help:studio',
      category: 'admin',
      kind: 'answer',
      title: 'Review a Studio brief',
      summary:
        'Studio briefs are collected in one place so the team can review the request, read the message, and update the status clearly.',
      label: 'Studio',
      href: '/admin?tab=studio',
      destination: 'Studio tab',
      actionLabel: 'Open Studio',
      keywords: [
        'studio',
        'brief',
        'custom request',
        'space advice',
        'client brief',
        'reference image',
      ],
      steps: [
        'Open Studio.',
        'Choose the brief you want to review.',
        'Read the customer message and any uploaded reference.',
        'Update the status and add internal notes if the team needs context.',
        'Save the brief so the inbox stays current.',
      ],
    },
    {
      id: 'admin-help:reviews',
      category: 'admin',
      kind: 'answer',
      title: 'Approve, reject, or feature a review',
      summary:
        'The Reviews area is where you manage customer reviews and decide what appears on the storefront.',
      label: 'Reviews',
      href: '/admin?tab=reviews',
      destination: 'Reviews tab',
      actionLabel: 'Open Reviews',
      keywords: [
        'review',
        'approve review',
        'feature review',
        'customer feedback',
        'rating',
        'testimonials',
      ],
      steps: [
        'Open Reviews.',
        'Choose the review you want to manage.',
        'Read the rating and message.',
        'Approve it, remove it from display, or mark it as featured.',
        'Save the update so the product page shows the right review state.',
      ],
    },
    {
      id: 'admin-help:contact',
      category: 'admin',
      kind: 'answer',
      title: 'Find and handle a contact message',
      summary:
        'Contact requests can be searched by name, email, subject, or message so the team can respond and mark progress quickly.',
      label: 'Contact',
      href: '/admin?tab=contact',
      destination: 'Contact tab',
      actionLabel: 'Open Contact',
      keywords: [
        'contact message',
        'support',
        'customer email',
        'reply',
        'mark handled',
        'contact us',
      ],
      steps: [
        'Open Contact.',
        'Search by the customer name, email, or subject line.',
        'Open the message and read the details.',
        'Update the status to show whether it is new, read, or handled.',
        'Use the customer details to follow up outside the dashboard if needed.',
      ],
    },
    {
      id: 'admin-help:newsletter',
      category: 'admin',
      kind: 'answer',
      title: 'Create or manage a newsletter',
      summary:
        'Use the Newsletter workspace to work with subscribers, open the email builder, and prepare campaigns with article content.',
      label: 'Newsletter',
      href: '/admin/newsletter',
      destination: 'Newsletter workspace',
      actionLabel: 'Open Newsletter',
      keywords: [
        'newsletter',
        'email marketing',
        'hubspot',
        'subscriber',
        'campaign',
        'article email',
        'email builder',
      ],
      steps: [
        'Open the Newsletter workspace.',
        'Review the subscriber list or sync it with the email tool if needed.',
        'Choose or write the content you want to send.',
        'Open the email builder to design the newsletter.',
        'Test the content first, then send it to the right audience.',
      ],
    },
    {
      id: 'admin-help:content',
      category: 'admin',
      kind: 'answer',
      title: 'Edit page text, images, or sections',
      summary:
        'The Content workspace lets you update page copy, replace images, and manage repeated sections without touching code or JSON.',
      label: 'Content',
      href: '/admin/content',
      destination: 'Content workspace',
      actionLabel: 'Open Content',
      keywords: [
        'edit page',
        'change about page',
        'change contact page',
        'cms',
        'content',
        'update text',
        'replace image',
        'page editor',
        managedPageList,
      ],
      steps: [
        'Open the Content workspace.',
        'Choose the page you want to change.',
        'Edit the text directly in the fields you see on screen.',
        'Upload, replace, or remove images where needed.',
        'Save the page and use Preview if you want to check the result first.',
      ],
    },
    {
      id: 'admin-help:visibility',
      category: 'admin',
      kind: 'answer',
      title: 'Show or hide a website section',
      summary:
        'Section visibility is managed inside the Content area of the admin dashboard so you can turn key storefront sections on or off quickly.',
      label: 'Content',
      href: '/admin?tab=content',
      destination: 'Content tab',
      actionLabel: 'Open Content',
      keywords: [
        'hide section',
        'show section',
        'visibility',
        'turn off page section',
        'homepage section',
        'footer section',
      ],
      steps: [
        'Open the Content tab in admin.',
        'Find the section visibility list.',
        'Choose whether the section should be visible or hidden.',
        'Wait for the change to save.',
        'Refresh the storefront page if you want to confirm the change.',
      ],
    },
    {
      id: 'admin-help:automation',
      category: 'admin',
      kind: 'answer',
      title: 'Run the operations automation pass',
      summary:
        'The overview page includes a direct action that advances due orders, queues delivery follow-ups, and prepares review requests.',
      label: 'Overview',
      href: '/admin?tab=overview',
      destination: 'Overview tab',
      actionLabel: 'Open Overview',
      keywords: [
        'automation',
        'operations pass',
        'advance orders',
        'review requests',
        'delivery check in',
        'fulfillment',
      ],
      steps: [
        'Open Overview.',
        'Find the Quick actions panel.',
        'Choose Run operations pass.',
        'Wait for the summary message to appear.',
        'Review the updated orders, delivery reminders, or review requests if anything moved.',
      ],
    },
    {
      id: 'admin-help:exports',
      category: 'admin',
      kind: 'answer',
      title: 'Export orders, analytics, or subscribers',
      summary:
        'Exports are available from the relevant admin sections so you can take the latest data into spreadsheets or reporting tools.',
      label: 'Exports',
      href: '/admin?tab=newsletter',
      destination: 'Admin exports',
      actionLabel: 'Open Admin',
      keywords: [
        'export',
        'csv',
        'download orders',
        'download subscribers',
        'analytics export',
        'signals export',
      ],
      steps: [
        'Open the section that holds the data you need.',
        'Use the export button for that area, such as orders, analytics, or newsletter.',
        'Wait for the CSV download to start.',
        'Open the file in Sheets or Excel if you want to sort or report on it.',
      ],
    },
  ];
}
