import { imageByKey } from './site';

export type Product = {
  slug: string; category: 'indoor'|'outdoor'|'pots'; size: string; badge?: string; sku: string;
  name: string; short: string; rating: number; reviews: number; price: number; potOnly: number | null;
  description: string; cardDescription: string; image: string; gallery?: string[]; decorative?: boolean; forcePotOnly?: boolean;
  details: Record<string,string>; plantGuide?: Record<string,string>;
};

export const products: Product[] = [
  { slug:'ribbed-globe-peace-lily', category:'indoor', size:'small', badge:'Indoor', sku:'TP-GLOBE-SM-001', name:'Ribbed Globe Pot with Peace Lily', short:'with Peace Lily', rating:4.5, reviews:24, price:1800, potOnly:900, description:'Our signature ribbed globe is hand-thrown on the wheel over 25 minutes, creating subtle variations in each rib. The natural terracotta breathes, allowing air to reach the roots of your Peace Lily. Each pot is fired twice for maximum durability.', cardDescription:'A plump ribbed globe in classic terracotta. The ribbed texture adds grip and character.', plantGuide:{watering:'Weekly', light:'Low to medium indirect', temperature:'18–30°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'12cm x 14cm', weight:'420g', shape:'Round', finish:'Natural Terracotta'}, image:imageByKey.indoor1 },
  { slug:'pedestal-bowl-succulents', category:'indoor', size:'small', badge:'New', sku:'TP-BOWL-SM-002', name:'Pedestal Bowl with Succulents', short:'with Succulents', rating:4.3, reviews:18, price:2200, potOnly:1100, description:'The pedestal bowl combines form and function with a raised base that provides excellent drainage and airflow. Perfect for creating stunning succulent gardens.', cardDescription:'Wide-mouth bowl on a conical foot. Ideal for succulent arrangements and low trailing plants.', plantGuide:{watering:'Every 10 days', light:'Bright indirect', temperature:'18–29°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'16cm x 18cm', weight:'510g', shape:'Bowl', finish:'Natural Terracotta'}, image:imageByKey.indoor2 },
  { slug:'cylinder-vase-snake-plant', category:'indoor', size:'small', badge:'Indoor', sku:'TP-CYL-SM-003', name:'Cylinder Vase with Snake Plant', short:'with Snake Plant', rating:4.7, reviews:31, price:1500, potOnly:800, description:'The cylinder vase features clean, modern lines that complement any interior. The narrow opening supports tall, upright plants beautifully.', cardDescription:'Elegant hourglass profile in warm terracotta. Suits upright plants like snake plant or bamboo.', plantGuide:{watering:'Every 2 weeks', light:'Low to bright indirect', temperature:'18–32°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'10cm x 22cm', weight:'390g', shape:'Cylinder', finish:'Natural Terracotta'}, image:imageByKey.indoor3 },
  { slug:'jug-handle-pothos', category:'indoor', size:'medium', badge:'Indoor', sku:'TP-JUG-MD-004', name:'Jug Handle Pot with Pothos', short:'with Pothos', rating:4.6, reviews:22, price:2800, potOnly:1400, description:'A charming jug-style pot with a sturdy handle, perfect for trailing plants that cascade beautifully over the sides. Handcrafted with traditional techniques.', cardDescription:'Charming handled jug for trailing pothos or ivy. The handle makes it easy to move.', plantGuide:{watering:'Weekly', light:'Medium indirect', temperature:'18–29°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'18cm x 22cm', weight:'680g', shape:'Jug / Round', finish:'Natural Terracotta'}, image:imageByKey.indoor4 },
  { slug:'wide-rim-monstera', category:'indoor', size:'large', badge:'New', sku:'TP-WIDE-LG-005', name:'Wide Rim Planter with Monstera', short:'with Monstera', rating:4.8, reviews:15, price:3200, potOnly:1600, description:'Our wide rim planter is designed for large, statement-making plants like Monstera. The generous rim provides a beautiful frame for trailing foliage.', cardDescription:'Deep wide-rim planter for statement indoor plants. Excellent drainage.', plantGuide:{watering:'Weekly', light:'Bright indirect', temperature:'20–30°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'24cm x 24cm', weight:'940g', shape:'Round', finish:'Natural Terracotta'}, image:imageByKey.indoor1 },
  { slug:'tapered-column-fiddle', category:'indoor', size:'medium', sku:'TP-TAP-MD-006', name:'Tapered Column with Fiddle Leaf Fig', short:'with Fiddle Leaf Fig', rating:4.4, reviews:19, price:2600, potOnly:1300, description:'The tapered column is a modern take on classic terracotta. Its elegant proportions make it ideal for medium to large plants.', cardDescription:'Deep tapered column for dramatic indoor statement plants. Matte terracotta finish.', plantGuide:{watering:'Weekly', light:'Bright filtered', temperature:'18–28°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'16cm x 28cm', weight:'740g', shape:'Cylinder', finish:'Matte Terracotta'}, image:imageByKey.indoor2 },
  { slug:'ribbed-globe-medium-zz', category:'indoor', size:'medium', sku:'TP-GLOBE-MD-007', name:'Ribbed Globe Medium with ZZ Plant', short:'with ZZ Plant', rating:4.5, reviews:16, price:2100, potOnly:1050, description:'A larger version of the popular ribbed globe, scaled up for medium-sized plants while retaining the signature ribbed texture.', cardDescription:'Medium version of our beloved ribbed globe. Perfect for ZZ plants.', plantGuide:{watering:'Every 2 weeks', light:'Low to bright indirect', temperature:'18–30°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'15cm x 18cm', weight:'590g', shape:'Round', finish:'Natural Terracotta'}, image:imageByKey.indoor3 },
  { slug:'smooth-bowl-aloe', category:'indoor', size:'small', sku:'TP-SMO-SM-008', name:'Smooth Bowl with Aloe Vera', short:'with Aloe Vera', rating:4.2, reviews:12, price:1900, potOnly:950, description:'A clean, smooth bowl that lets the plant take center stage. Minimal design for modern interiors.', cardDescription:'Simple smooth bowl with a clean profile. Perfect for aloe vera.', plantGuide:{watering:'Every 2 weeks', light:'Bright light', temperature:'18–32°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'14cm x 12cm', weight:'360g', shape:'Bowl', finish:'Smooth Terracotta'}, image:imageByKey.indoor4 },
  { slug:'tall-cylinder-bamboo', category:'indoor', size:'large', sku:'TP-TCYL-LG-009', name:'Tall Cylinder with Bamboo', short:'with Bamboo', rating:4.6, reviews:9, price:3400, potOnly:1700, description:'Our tallest indoor cylinder, designed for bamboo and other dramatic vertical plants. A true statement piece.', cardDescription:'Extra tall cylinder for dramatic bamboo or tall plants.', plantGuide:{watering:'Weekly', light:'Bright indirect', temperature:'18–29°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'18cm x 34cm', weight:'880g', shape:'Cylinder', finish:'Natural Terracotta'}, image:imageByKey.indoor1 },
  { slug:'studio-jug-ivy', category:'indoor', size:'medium', sku:'TP-SJUG-MD-010', name:'Studio Jug with Ivy', short:'with Ivy', rating:4.3, reviews:14, price:2500, potOnly:1250, description:'A wider-bodied version of our jug pot, with more room for root growth and a generous opening for trailing plants.', cardDescription:'Studio-crafted jug with a wider body. Perfect for trailing ivy.', plantGuide:{watering:'Weekly', light:'Medium indirect', temperature:'18–27°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'17cm x 22cm', weight:'650g', shape:'Jug / Round', finish:'Natural Terracotta'}, image:imageByKey.indoor2 },
  { slug:'wide-mouth-spider', category:'indoor', size:'small', sku:'TP-WDMO-SM-011', name:'Wide Mouth Pot with Spider Plant', short:'with Spider Plant', rating:4.4, reviews:20, price:1700, potOnly:850, description:'Designed with a generous opening that lets spider plant babies cascade freely. Classic terracotta charm.', cardDescription:'Wide opening perfect for spider plants with cascading babies.', plantGuide:{watering:'Weekly', light:'Bright indirect', temperature:'16–29°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'14cm x 13cm', weight:'400g', shape:'Round', finish:'Natural Terracotta'}, image:imageByKey.indoor3 },
  { slug:'deep-planter-bird', category:'indoor', size:'large', badge:'Bestseller', sku:'TP-DEEP-LG-012', name:'Deep Planter with Bird of Paradise', short:'with Bird of Paradise', rating:4.9, reviews:28, price:4800, potOnly:2400, description:'The deep planter is our premium indoor pot, designed for large tropical plants. Double-fired for extra strength, with a generous depth for robust root systems.', cardDescription:'Our deepest planter for large statement plants like Bird of Paradise.', plantGuide:{watering:'Weekly', light:'Bright indirect', temperature:'18–32°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'28cm x 30cm', weight:'1.4kg', shape:'Deep Planter', finish:'Natural Terracotta'}, image:imageByKey.indoor4 },
  { slug:'studio-collection-agave', category:'outdoor', size:'large', badge:'Outdoor', sku:'TP-STUD-LG-013', name:'Studio Collection with Agave & Aloe', short:'with Agave & Aloe', rating:4.7, reviews:20, price:4500, potOnly:2250, description:'The Studio Collection represents our finest outdoor work. Each pot is hand-thrown by our master potter, designed to withstand all weather conditions.', cardDescription:'Our signature large outdoor pots hand-thrown in the studio.', plantGuide:{watering:'Every 2 weeks', light:'Full sun', temperature:'20–34°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'30cm x 32cm', weight:'1.8kg', shape:'Studio Form', finish:'Weathered Terracotta'}, image:imageByKey.outdoor1 },
  { slug:'hut-sculpture-garden', category:'outdoor', size:'decorative', badge:'Outdoor', sku:'TP-HUT-DC-014', name:'Hut Sculpture with Garden Ornament', short:'garden ornament', rating:4.8, reviews:32, price:3500, potOnly:null, description:'This one-of-a-kind hut sculpture is entirely handcrafted, from the walls to the thatched roof detail. A conversation piece for any garden.', cardDescription:'A unique thatched-roof hut. Doubles as bird feeder or garden ornament.', decorative:true, details:{material:'100% Natural Kenyan Clay', dimensions:'20cm x 24cm', weight:'900g', shape:'Sculptural', finish:'Natural Terracotta'}, image:imageByKey.outdoor2 },
  { slug:'ribbed-cylinder-xl-bougainvillea', category:'outdoor', size:'large', sku:'TP-RCYL-LG-015', name:'Ribbed Cylinder XL with Bougainvillea', short:'with Bougainvillea', rating:4.5, reviews:14, price:3800, potOnly:1900, description:'An oversized version of our ribbed cylinder, built with thicker walls for outdoor durability. Perfect for vigorous climbers like bougainvillea.', cardDescription:'Extra large ribbed cylinder built for outdoor use with climbing plants.', plantGuide:{watering:'Twice weekly', light:'Full sun', temperature:'18–34°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'26cm x 34cm', weight:'1.6kg', shape:'Cylinder', finish:'Natural Terracotta'}, image:imageByKey.outdoor3 },
  { slug:'round-belly-lavender', category:'outdoor', size:'medium', badge:'New', sku:'TP-BELL-MD-016', name:'Round Belly Pot with Lavender', short:'with Lavender', rating:4.4, reviews:11, price:2400, potOnly:1200, description:'The round belly pot is a timeless shape, ideal for herbs and aromatic plants that thrive in outdoor conditions.', cardDescription:'Classic belly-pot shape for herbs and aromatics. Beautiful on patios.', plantGuide:{watering:'Twice weekly', light:'Full sun', temperature:'18–32°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'19cm x 20cm', weight:'740g', shape:'Round', finish:'Natural Terracotta'}, image:imageByKey.outdoor4 },
  { slug:'ribbed-globe-xl-bird', category:'outdoor', size:'large', sku:'TP-GLOB-LG-017', name:'Ribbed Globe XL with Bird of Paradise', short:'with Bird of Paradise', rating:4.6, reviews:8, price:5200, potOnly:2600, description:'An oversized ribbed globe for dramatic outdoor plantings. The iconic ribbed texture scaled up for maximum impact.', cardDescription:'XL version of our beloved ribbed globe. Deep enough for large root systems.', plantGuide:{watering:'Weekly', light:'Bright sun', temperature:'18–33°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'32cm x 34cm', weight:'2kg', shape:'Round', finish:'Natural Terracotta'}, image:imageByKey.outdoor1 },
  { slug:'pedestal-garden-cacti', category:'outdoor', size:'medium', badge:'Outdoor', sku:'TP-PBWL-MD-018', name:'Pedestal Garden Bowl with Cacti Mix', short:'with Cacti Mix', rating:4.3, reviews:16, price:3000, potOnly:1500, description:'An outdoor-rated pedestal bowl with enhanced drainage, perfect for creating stunning cacti and succulent gardens.', cardDescription:'Wide pedestal bowl for a cacti garden arrangement on garden paths.', plantGuide:{watering:'Every 2 weeks', light:'Full sun', temperature:'20–35°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'22cm x 16cm', weight:'860g', shape:'Bowl', finish:'Natural Terracotta'}, image:imageByKey.outdoor2 },
  { slug:'wide-rim-bougainvillea', category:'outdoor', size:'medium', sku:'TP-WRMG-MD-019', name:'Wide Rim Garden Pot with Rosemary', short:'with Rosemary', rating:4.5, reviews:19, price:2800, potOnly:1400, description:'A garden-rated version of our wide rim design, built with thicker walls for outdoor durability.', cardDescription:'Wide rim garden pot, perfect for herbs and aromatic plants.', plantGuide:{watering:'Twice weekly', light:'Full sun', temperature:'18–32°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'20cm x 18cm', weight:'780g', shape:'Round', finish:'Natural Terracotta'}, image:imageByKey.outdoor3 },
  { slug:'jug-garden-ferns', category:'outdoor', size:'medium', sku:'TP-JGRN-MD-020', name:'Jug Garden Vessel with Ferns', short:'with Ferns', rating:4.4, reviews:10, price:3200, potOnly:1600, description:'An oversized garden jug perfect for shaded garden corners where ferns thrive.', cardDescription:'Garden-scale jug vessel for shade-loving ferns.', plantGuide:{watering:'Weekly', light:'Partial shade', temperature:'16–28°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'24cm x 24cm', weight:'980g', shape:'Jug', finish:'Natural Terracotta'}, image:imageByKey.outdoor4 },
  { slug:'studio-xl-deep-palm', category:'outdoor', size:'large', badge:'Bestseller', sku:'TP-STXL-LG-021', name:'Studio XL Deep with Date Palm', short:'with Date Palm', rating:4.9, reviews:25, price:6500, potOnly:3250, description:'The Studio XL Deep is our most ambitious pot, designed for small trees and large palms. Hand-thrown by our master potter.', cardDescription:'Our largest studio pot. Made for date palms and trees.', plantGuide:{watering:'Twice weekly', light:'Full sun', temperature:'20–35°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'38cm x 42cm', weight:'2.8kg', shape:'Deep Studio', finish:'Natural Terracotta'}, image:imageByKey.outdoor1 },
  { slug:'hut-mini-bird', category:'outdoor', size:'decorative', sku:'TP-HMNI-DC-022', name:'Hut Mini with Bird Feeder', short:'bird feeder', rating:4.7, reviews:21, price:2200, potOnly:null, description:'A scaled-down version of our signature hut, designed to attract small garden birds.', cardDescription:'Miniature hut sculpture doubling as a charming bird feeder.', decorative:true, details:{material:'100% Natural Kenyan Clay', dimensions:'12cm x 16cm', weight:'460g', shape:'Sculptural', finish:'Natural Terracotta'}, image:imageByKey.outdoor2 },
  { slug:'ribbed-tall-garden-canna', category:'outdoor', size:'large', sku:'TP-RTGR-LG-023', name:'Ribbed Tall Garden with Canna Lily', short:'with Canna Lily', rating:4.5, reviews:12, price:4200, potOnly:2100, description:'A tall ribbed pot built for outdoor drama. The vertical ribbing adds both strength and visual elegance.', cardDescription:'Tall ribbed outdoor pot for dramatic flowering plants.', plantGuide:{watering:'Twice weekly', light:'Full sun', temperature:'20–34°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'24cm x 38cm', weight:'1.9kg', shape:'Tall Cylinder', finish:'Natural Terracotta'}, image:imageByKey.outdoor3 },
  { slug:'belly-pot-lemon', category:'outdoor', size:'large', sku:'TP-BELL-LG-024', name:'Belly Pot Large with Lemon Tree', short:'with Lemon Tree', rating:4.8, reviews:7, price:5800, potOnly:2900, description:'Our largest belly pot, designed for small fruit trees like lemon. The wide belly provides ample root space.', cardDescription:'Extra large belly pot for fruit trees and large shrubs.', plantGuide:{watering:'Twice weekly', light:'Full sun', temperature:'18–34°C'}, details:{material:'100% Natural Kenyan Clay', dimensions:'36cm x 34cm', weight:'2.4kg', shape:'Round Belly', finish:'Natural Terracotta'}, image:imageByKey.outdoor4 },
  { slug:'ribbed-globe-solo', category:'pots', size:'small', badge:'Pot Only', sku:'TP-GLOB-SO-025', name:'Ribbed Globe', short:'Round · Natural Terracotta', rating:4.5, reviews:42, price:900, potOnly:null, description:'The naked ribbed globe, ready for your own plant choice. Beautiful natural terracotta with handmade character.', cardDescription:'Just the pot. Our classic ribbed globe in natural terracotta.', details:{material:'100% Natural Kenyan Clay', dimensions:'12cm x 14cm', weight:'320g', shape:'Round', finish:'Natural Terracotta'}, image:imageByKey.productStudio, forcePotOnly:true },
  { slug:'pedestal-bowl-solo', category:'pots', size:'small', badge:'Pot Only', sku:'TP-BOWL-SO-026', name:'Pedestal Bowl', short:'Bowl · Natural Terracotta', rating:4.3, reviews:28, price:1100, potOnly:null, description:'A versatile pedestal bowl that works with succulents, herbs, or any low-growing plant you choose.', cardDescription:'Wide pedestal bowl in natural terracotta. Add your own plants.', details:{material:'100% Natural Kenyan Clay', dimensions:'14cm x 12cm', weight:'350g', shape:'Bowl', finish:'Natural Terracotta'}, image:imageByKey.productStudio, forcePotOnly:true },
  { slug:'cylinder-vase-solo', category:'pots', size:'small', badge:'Pot Only', sku:'TP-CYL-SO-027', name:'Cylinder Vase', short:'Cylinder · Natural Terracotta', rating:4.7, reviews:35, price:800, potOnly:null, description:'Clean cylinder lines in warm terracotta. Perfect for tall plants or even as a standalone decorative piece.', cardDescription:'Elegant cylinder vase in natural terracotta.', details:{material:'100% Natural Kenyan Clay', dimensions:'10cm x 20cm', weight:'280g', shape:'Cylinder', finish:'Natural Terracotta'}, image:imageByKey.productStudio, forcePotOnly:true },
  { slug:'jug-handle-solo', category:'pots', size:'medium', badge:'Pot Only', sku:'TP-JUG-SO-028', name:'Jug Handle Pot', short:'Jug/Round · Natural Terracotta', rating:4.6, reviews:18, price:1400, potOnly:null, description:'The jug handle pot, ready for your choice of trailing or upright plant. The handle adds character and functionality.', cardDescription:'Handcrafted jug with handle. Natural terracotta finish.', details:{material:'100% Natural Kenyan Clay', dimensions:'16cm x 20cm', weight:'480g', shape:'Jug / Round', finish:'Natural Terracotta'}, image:imageByKey.productStudio, forcePotOnly:true },
  { slug:'hut-sculpture-solo', category:'pots', size:'decorative', badge:'Pot Only', sku:'TP-HUT-SO-029', name:'Hut Sculpture', short:'Sculptural · Natural Terracotta', rating:4.8, reviews:32, price:2200, potOnly:null, description:'A purely decorative hut sculpture that adds artisanal charm to any space. Each one is unique.', cardDescription:'Unique handcrafted hut sculpture. A garden conversation piece.', decorative:true, details:{material:'100% Natural Kenyan Clay', dimensions:'16cm x 18cm', weight:'520g', shape:'Sculptural', finish:'Natural Terracotta'}, image:imageByKey.productStudio, forcePotOnly:true },
  { slug:'ribbed-cylinder-solo', category:'pots', size:'large', badge:'Pot Only', sku:'TP-RCYL-SO-030', name:'Ribbed Cylinder', short:'Cylinder · Natural Terracotta', rating:4.5, reviews:15, price:1900, potOnly:null, description:'A substantial ribbed cylinder that makes a bold statement. Perfect for medium to large plants.', cardDescription:'Large ribbed cylinder in natural terracotta.', details:{material:'100% Natural Kenyan Clay', dimensions:'18cm x 28cm', weight:'860g', shape:'Cylinder', finish:'Natural Terracotta'}, image:imageByKey.productStudio, forcePotOnly:true },
  { slug:'wide-rim-solo', category:'pots', size:'medium', badge:'Pot Only', sku:'TP-WIDE-SO-031', name:'Wide Rim Planter', short:'Round · Natural Terracotta', rating:4.4, reviews:22, price:1600, potOnly:null, description:'Our wide rim planter without a plant, ready for your own choice. The generous rim adds visual interest.', cardDescription:'Wide rim planter in natural terracotta. Great for any large plant.', details:{material:'100% Natural Kenyan Clay', dimensions:'18cm x 16cm', weight:'560g', shape:'Round', finish:'Natural Terracotta'}, image:imageByKey.productStudio, forcePotOnly:true },
  { slug:'tapered-column-solo', category:'pots', size:'medium', badge:'Pot Only', sku:'TP-TAP-SO-032', name:'Tapered Column', short:'Cylinder · Natural Terracotta', rating:4.4, reviews:14, price:1300, potOnly:null, description:'A modern tapered column, clean and minimalist. Ideal for a wide range of plants.', cardDescription:'Tapered column pot in matte natural terracotta.', details:{material:'100% Natural Kenyan Clay', dimensions:'14cm x 24cm', weight:'440g', shape:'Cylinder', finish:'Matte Natural Terracotta'}, image:imageByKey.productStudio, forcePotOnly:true },
  { slug:'round-belly-solo', category:'pots', size:'medium', badge:'Pot Only', sku:'TP-BELL-SO-033', name:'Round Belly Pot', short:'Round · Natural Terracotta', rating:4.3, reviews:17, price:1200, potOnly:null, description:'The timeless round belly pot, a classic shape that works beautifully in any setting.', cardDescription:'Classic round belly shape in natural terracotta.', details:{material:'100% Natural Kenyan Clay', dimensions:'15cm x 16cm', weight:'420g', shape:'Round', finish:'Natural Terracotta'}, image:imageByKey.productStudio, forcePotOnly:true },
  { slug:'workshop-set', category:'pots', size:'sets', badge:'Bestseller', sku:'TP-SET-MX-034', name:'Studio Workshop Set', short:'Mixed Set · Natural Terracotta', rating:4.9, reviews:38, price:6500, potOnly:null, description:'A hand-picked set of 4 different pot styles from our workshop. Each set is unique, featuring a mix of sizes and shapes.', cardDescription:'Set of 4 mixed pots from our studio. A curated collection.', details:{material:'100% Natural Kenyan Clay', dimensions:'Mixed set of 4', weight:'3.2kg', shape:'Mixed Set', finish:'Natural Terracotta'}, image:imageByKey.productStudio, forcePotOnly:true }
];

export const productBySlug = Object.fromEntries(products.map((p) => [p.slug, p]));
export const studioCard = { slug:'studio-collection-request', category:'studio', name:'Studio Collection', short:'custom commissions', rating:5, reviews:12, price:0, image:imageByKey.clay, badge:'Members', cardDescription:'Upload inspirations, tell us quantities, and let our guided studio assistant shape your brief.' };

export const sizeOptionsFor = (product: Product) => {
  if (product.size === 'sets') return [{ key:'set', label:'Studio Set', helper:'Set of 4 pots', multiplier:1 }];
  if (product.decorative) return [{ key:'small', label:'Small', helper:'Easy to style', multiplier:1 }, { key:'medium', label:'Medium', helper:'Most popular size', multiplier:1.18 }, { key:'large', label:'Large', helper:'Makes a statement', multiplier:1.35 }];
  if (product.size === 'small') return [{ key:'small', label:'Small', helper:'Great for desks', multiplier:1 }, { key:'medium', label:'Medium', helper:'Easy for shelves', multiplier:1.2 }, { key:'large', label:'Large', helper:'Nice for floors', multiplier:1.42 }];
  if (product.size === 'medium') return [{ key:'small', label:'Small', helper:'Slightly smaller', multiplier:0.9 }, { key:'medium', label:'Medium', helper:'Most popular size', multiplier:1 }, { key:'large', label:'Large', helper:'Nice for floors', multiplier:1.22 }, { key:'xl', label:'Extra Large', helper:'Best for patios', multiplier:1.45 }];
  return [{ key:'medium', label:'Medium', helper:'Easy to place', multiplier:0.82 }, { key:'large', label:'Large', helper:'Nice for floors', multiplier:1 }, { key:'xl', label:'Extra Large', helper:'Best for patios', multiplier:1.2 }];
};

export const faqItems = [
  ['Are TuloPots really handmade?', 'Yes! Every single pot is hand-thrown on a potter\'s wheel by our skilled artisans in Nairobi. No two pots are exactly alike — each carries the subtle variations that make handcrafted pottery special.'],
  ['What clay do you use?', 'We use 100% natural Kenyan clay sourced from local deposits. Our clay is processed and aged before shaping to support durability and beautiful finish.'],
  ['Do your pots have drainage holes?', 'All plant-ready pots come with drainage holes. Decorative pieces may not. Always check the product detail page.'],
  ['How do I care for my terracotta pot?', 'Terracotta is naturally porous and breathable. Avoid freezing temperatures, clean with a damp cloth, and occasionally soak in water to prevent salt buildup.'],
  ['Do you deliver outside Nairobi?', 'Yes, we deliver across Kenya. Nairobi deliveries are free for orders above KSh 5,000.'],
  ['Can I order pots without plants?', 'Absolutely. Eligible pairings are available as clay forms, and our Clay Forms collection is ready for customers who already have plants.'],
  ['Do you accept custom orders?', 'Yes. Signed-in customers can use Studio Collection to upload inspirations and start a guided brief.'],
  ['What is your return policy?', 'We offer a 30-day satisfaction guarantee for pots. Contact us if something arrives damaged or not as expected.']
] as const;
